// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "custom/changeSelectedPrice"
import "custom/menu"
import "@nathanvda/cocoon"
import "admin"
import "user"
import "custom/tab"
import "custom/autoCalculate"
import "custom/formReview"
import "chartkick"
import "Chart.bundle"
